security:
  referrerPolicy: origin
idam:
  client_id: paybubble
  login_url: http://localhost:23443/login
  api_url: http://localhost:23443
session:
  cookieName: SESSION_ID
environment:
  ldPrefix: FElocal
ccpaybubble:
  url: https://localhost
  defaultPort: 3000
  microservice: ccpay_bubble
pcipalantenna:
  url: https://localhost
  microservice: ccpay_bubble
s2s:
  url: http://localhost:23443
payhub:
  url: http://localhost:8080
bulkscan:
  url: http://localhost:8081
appInsights:
  roleName: paybubble
e2e:
  frontendUrl: https://localhost:4200/
  waitForTimeoutValue: 2600
  waitForActionValue: 2000
certs:
  key: ./localhost-ssl/localhost.key
  crt: ./localhost-ssl/localhost.crt
fee:
  feeRegistrationUrl: http://localhost:23443/fees
  feeJurisdictionUrl: http://localhost:23443/jurisdictions
ccd:
  url: http://localhost:23443
secrets:
  ccpay:
    paybubble-s2s-secret: G5XTFNBUW4P6ZP4F
    paybubble-idam-client-secret: NVYEC2X7XFSRENTU
    launch-darkly-client-id: 5f227f4df775300ba82996dc
    AppInsightsInstrumentationKey: some-key
