security:
  referrerPolicy: origin
idam:
  client_id: paybubble
  client_secret: NVYEC2X7XFSRENTU
  login_url: http://localhost:23443/login
  api_url: http://localhost:23443
session:
  cookieName: SESSION_ID
ccpaybubble:
  url: https://localhost
  defaultPort: 3000
  microservice: ccpay_bubble
s2s:
  key: G5XTFNBUW4P6ZP4F
  url: http://localhost:23443
payhub:
  url: http://localhost:8080
appInsights:
  instrumentationKey: some-key
  roleName: paybubble
e2e:
  frontendUrl: https://localhost:4200/
  waitForTimeoutValue: 2600
  waitForActionValue: 2000
certs:
  key: ./localhost-ssl/localhost.key
  crt: ./localhost-ssl/localhost.crt
fee:
  feeRegistrationUrl: http://localhost:23443/fees
  feeJurisdictionUrl: http://localhost:23443/jurisdictions
  